version: '3.7'

services:
  keycloak:
    container_name: keycloak22
    image: quay.io/keycloak/keycloak:24.0
    volumes:
      - ./theme:/opt/keycloak/themes:ro # this is for custom theme
      - ./plugins:/opt/keycloak/providers:ro
      - db-data1:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    ports:
      - 8080:8080
      - 5432:5432/udp
      - 5432:5432

volumes:
  db-data1: {}
